### ISSUE TITLE
Code rot has broken swi-chat

### ISSUE THREAD

**Issue by Anniepoo** [JanWielemaker/swi-chat#2]
checking out head on my machine and double click starting debug.pl gives

ERROR: c:/docs/laserbiz/marketing/bannerads/toucangame/swi-chat/hub.pl:184:
        Functions are not (yet) supported for meta-arguments of type 1
Welcome to SWI-Prolog (Multi-threaded, 64 bits, Version 7.1.29-5-g0a3d88a)
Copyright (c) 1990-2014 University of Amsterdam, VU Amsterdam
SWI-Prolog comes with ABSOLUTELY NO WARRANTY. This is free software,
and you are welcome to redistribute it under certain conditions.
Please visit http://www.swi-prolog.org for details.

For help, use ?- help(Topic). or ?- apropos(Word).

1 ?- 

This apparently is bit rot with swi-prolog, as I'm getting the same with whiteboard, which is quite a ways behind swi-chat.

**Comment by JanWielemaker** [comment]
Yip.  Over enthusiastic error reporting.  Fixed in SWI-Prolog/swipl-devel@7763358ced8ef6fa26819b76cad3355dd537d28d.
